### ISSUE TITLE
Strange error message is thrown if appPackage caps contains white space at its end

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#15]
By running `AVD8_FOR_MAGIC_POD=Nexus_5_API_26 npm run test -- --grep "should work with Android8 emulator with Java9:"` with the following temporal change (I added white space to appPackage and set noReset=true),

<img width="1093" alt="screen shot 2018-05-18 at 15 46 59" src="https://user-images.githubusercontent.com/4276719/40220057-cab3a4c2-5ab2-11e8-8503-2c4e7637879c.png">

I encountered the unexpected error `java.lang.IllegalArgumentException: Bad component name: com.android.vending`.

[Server log](https://gist.github.com/NozomiIto/bddb90c1c5df8f34e9e37eef19e0fd60)

I think error message such as `package does not exist` should be thrown or space chars should be trimmed.

**Comment by NozomiIto** [comment]
Tail/head white space for appPackage/appActivity also may cause similar problem, though I have not checked it.

**Comment by KazuCocoa** [comment]
I understand the situation.

Personally, it's better to have no responsibility for modifying or changing capability in Appium side. The capability sections are set by users and Appium has already type like String/Integer, etc. So, as Appium, we should guide users to set capability correctly.

Thus, I'll try to ensure error message.

**Comment by KazuCocoa** [comment]
The message is comes from `adb` command itself.

hm...
We shouldn't change the message...

But can we suggest users to ensure the capability...?

**Comment by NozomiIto** [comment]
> But should we suggest users to ensure the capability...?

I think Appium user cannot understand this error message.
If adb assume its arugment package name does not contain invalid chars like space, Appium should check if the package name contains such chars before calling adb, I think.

**Comment by NozomiIto** [comment]
Thank you!!

**Comment by KazuCocoa** [comment]
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

Maybe, `[a-zA-Z0-9_.]+`

**Comment by KazuCocoa** [comment]
Created a suggestion. https://github.com/appium/appium-android-driver/pull/371

**Comment by NozomiIto** [comment]
Thank you!
I'm afraid `appWaitPackage` also can contain astarisk.

**Comment by KazuCocoa** [comment]
merged.
