### ISSUE TITLE
Page source contents are sometimes broken

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#18]
The page source result of the following iOS page sometimes become invalid (this often happens in the second or later calls of the command)

<img width="245" alt="screen shot 2018-06-21 at 14 35 21" src="https://user-images.githubusercontent.com/4276719/41699762-5aaf2bec-7560-11e8-8f0c-8d0780781948.png">

### How to reproduce

1. `npm install` with the latest AppiumRegressionCheck code (I've added some dependencies to package.json)
2. Run `npm run test -- --grep "iOS source contents should be valid"` with Appium server 1.8.1.

This test sometimes passes for the first time. But when running it more than twice, it always fails in my PC..

- [Appium Sever log for the failed test](https://gist.github.com/NozomiIto/6f9c647415ee816ae180e216f04535a4)
- [Correct XML for this demo app](https://gist.github.com/NozomiIto/dfa022eb22053608a42d31b94a572fe1)
- [Invalid XML for the same screen in this demo app](https://gist.github.com/NozomiIto/88a7737aab2602de49bac0d0ed07eeca)

It does not seem to happen with Appium1.8.0. I'm afraid this is Appium1.8.1 problem.

**Comment by NozomiIto** [comment]
I tried this test with the appium latest master logic, but the situation is the same..

**Comment by KazuCocoa** [comment]
I'll run with the false once

**Comment by NozomiIto** [comment]
On my PC, this problem does not happen with `useJSONSource: false`. Happens only with `useJSONSource: true`

**Comment by KazuCocoa** [comment]
My local too.
Converting JSON to XML has the issue.

**Comment by KazuCocoa** [comment]
Maybe, something lost in https://github.com/appium/appium-xcuitest-driver/blob/4fa70fa6d03d766491bcb57604d47fcfef4ba6d5/lib/commands/source.js#L82-L96

**Comment by KazuCocoa** [comment]
I could see.

<details>
```
<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
  <XCUIElementTypeApplication type="XCUIElementTypeApplication" enabled="true" visible="true" x="30" y="304" width="315" height="56" name="登録" label="登録">
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="20" width="375" height="44" name="ユーザー登録">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
        <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" enabled="true" visible="true" x="0" y="0" width="375" height="667">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="688" width="112" height="22" name="登録しました！" label="登録しました！" value="登録しました！">
          </XCUIElementTypeOther>
        </XCUIElementTypeNavigationBar>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="100" width="375" height="56">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="218" width="74" height="21" name="    性別" label="    性別" value="    性別">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="200" width="375" height="56">
              <XCUIElementTypeTextField type="XCUIElementTypeTextField" enabled="true" visible="true" x="30" y="304" width="315" height="56" name="登録" label="登録">
                <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="false" x="0" y="667" width="375" height="64">
                </XCUIElementTypeStaticText>
              </XCUIElementTypeTextField>
              <XCUIElementTypeTextField type="XCUIElementTypeTextField" enabled="true" visible="true" x="0" y="0" width="375" height="667">
                <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="164" y="0" width="50" height="20" name="2:36 PM" label="2:36 PM">
                </XCUIElementTypeStaticText>
              </XCUIElementTypeTextField>
              <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="0" y="0" width="375" height="667">
              </XCUIElementTypeButton>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
                <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="6" y="0" width="39" height="20">
                </XCUIElementTypeStaticText>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeWindow>
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="50" y="0" width="15" height="20" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" value="SSID">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="20">
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeWindow>
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="164" y="0" width="50" height="20" name="2:39 PM" label="2:39 PM">
      <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="343" y="0" width="27" height="20" name="87% battery power" label="87% battery power">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="20">
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="20">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
          </XCUIElementTypeOther>
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="50" y="0" width="15" height="20" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" value="SSID">
          </XCUIElementTypeOther>
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="164" y="0" width="50" height="20" name="2:39 PM" label="2:39 PM">
          </XCUIElementTypeOther>
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="343" y="0" width="27" height="20" name="87% battery power" label="87% battery power">
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeStatusBar>
    </XCUIElementTypeWindow>
  </XCUIElementTypeApplication>
</AppiumAUT>
```
</details>

**Comment by KazuCocoa** [comment]
But the above is different from https://gist.github.com/NozomiIto/dfa022eb22053608a42d31b94a572fe1 

I called the command 5 times. They differed every time.
https://gist.github.com/KazuCocoa/963650f14f600f2d2b80e7e3f6d363a2

**Comment by KazuCocoa** [comment]
https://github.com/facebook/WebDriverAgent/blob/2c630efdf4927d0bcf6070c51511301fc954c28d/WebDriverAgentLib/Commands/FBDebugCommands.m#L47 In XML case, the code waits.
It probably trade off to get elements.

**Comment by KazuCocoa** [comment]
https://github.com/facebook/WebDriverAgent/blob/6832e20fbf0b1f8faf1f9a54171d4c7db9f45fb9/WebDriverAgentLib/Categories/XCUIApplication%2BFBHelpers.m#L41
In JSON case also the method is called

**Comment by KazuCocoa** [comment]
According to https://github.com/facebook/WebDriverAgent/blob/6832e20fbf0b1f8faf1f9a54171d4c7db9f45fb9/WebDriverAgentLib/Categories/XCUIApplication%2BFBHelpers.m#L54 , the code strongly depends on Apple framework...

**Comment by KazuCocoa** [comment]
The difference happens also in XML format: https://gist.github.com/KazuCocoa/963650f14f600f2d2b80e7e3f6d363a2#gistcomment-2627834

**Comment by KazuCocoa** [comment]
@NozomiIto 
The issue depends on Apple side.

Since I can see the issue both XML and JSON format. Code base in WDA is simple. Get data via Apple framework and map them to XML/JSON.

Hence, I think it's difficult to fix it by our side...

**Comment by NozomiIto** [comment]
@KazuCocoa 
Umm, this does not happen with Appium 1.8.0 or former. Why this happens now? I'm afraid there exist some kind code difference between Appium1.8.0 and Appium1.8.1.

**Comment by NozomiIto** [comment]
I took a look a the XML difference ( https://gist.github.com/KazuCocoa/963650f14f600f2d2b80e7e3f6d363a2#gistcomment-2627834 ).
And the difference of 2 XML is strange big invisible area.

<img width="1023" alt="screen shot 2018-06-23 at 16 05 44" src="https://user-images.githubusercontent.com/4276719/41806805-5cfda496-76ff-11e8-8985-879b4a5a47c6.png">

Although this difference is strange, it does not make a critical effect to know the app tree structure.
But as for json format result, the XML is much more broken, and it make it difficult to know the app tree structure...

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/pull/80 was affected?

**Comment by NozomiIto** [comment]
Thanks for checking.
I strongly feel so...

**Comment by KazuCocoa** [comment]
@NozomiIto 
What about following below lines and run tests on your local?

```
$ cd node_modules/appium-xcuitest-driver
$ vi WebDriverAgent/WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.m
# Apply https://github.com/appium/WebDriverAgent/compare/master...KazuCocoa:revert-since-wrong-arrtibutes?expand=1
$ npm run build
$ cd ../..
```

Mine: https://gist.github.com/KazuCocoa/019fd52553de320eaba5c3e474db0154

**Comment by NozomiIto** [comment]
This fix worked fine on my PC with the latest master code 😄 
This also worked well on you environment?

**Comment by KazuCocoa** [comment]
Yup, it worked on my env, too.
Let me create a PR to revert the change.

**Comment by KazuCocoa** [comment]
You can try out with the latest `appium@beta`

**Comment by KazuCocoa** [comment]
Close since the fix was released in `appium@beta`
Let me know if same error happens @NozomiIto
