### ISSUE TITLE
mobile: scroll sometimes does not work

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#19]
`npm test -- --grep "mobile: scroll should work"` with Appium 1.8.1 and latest test code in this repository fails. It seems `driver.execute("mobile: scroll", {element: element, toVisible: true})` sometimes does not work well.

This test code uses Xpath `//XCUIElementTypeStaticText[@name='Search Bars']/parent::*`, but I think this is not the problem related to Xpath, since the element is correctly found.

XML UI tree: https://gist.github.com/NozomiIto/82766ce44e02f0d58571788fa3bb6412

**Comment by KazuCocoa** [comment]
📝 
https://github.com/facebook/WebDriverAgent/blob/e92bce2de3200e1145b79f12709e17551b284bf4/WebDriverAgentLib/Commands/FBElementCommands.m#L275

---

@NozomiIto 
Could you attach your server logs as well?

**Comment by NozomiIto** [comment]
@KazuCocoa 
Server log: https://gist.github.com/NozomiIto/1d758407d75ca66f57bc9ca9a9054796

**Comment by KazuCocoa** [comment]
I think we have no changes affects this...
https://github.com/appium/WebDriverAgent/blame/master/WebDriverAgentLib/Commands/FBElementCommands.m#L269
Only changing indexing probably affects. But the way was more stable way.

**Comment by KazuCocoa** [comment]
I tried on my local with appium sample app. But it doesn't work well. Even 'Style Default' appears, appium tried to scroll further.

```
        el = @@core.wait { @@driver.find_element(:accessibility_id, 'Style Default') }
        @@driver.execute_script('mobile: scroll', {element: el.ref, toVisible: true})
```

**Comment by KazuCocoa** [comment]
As you know, `visibility` is unstable. So, I guess it sometimes works, but sometimes doesn't work...

On my env, below is more stable than `toVisible: true`...

```ruby
        while
          el = @@core.wait { @@driver.find_element(:xpath, "//XCUIElementTypeStaticText[@name='Style Default']/parent::*") }
          visibility = el.visible
          break if visibility == "true"
          @@driver.execute_script('mobile: scroll', direction: 'down')
        end
```

@NozomiIto 
What do you think implmenting like above?
(The above is Ruby though)

**Comment by NozomiIto** [comment]
@KazuCocoa Thanks! I will it later!

**Comment by NozomiIto** [comment]
@KazuCocoa 
This always failed with Appium1.8.1, but I've found this always succeeds with Appium1.9.0.
So I close this issue. Thanks!!
