### ISSUE TITLE
 Error: read ECONNRESET is thrown for iOS real device test while taking screenshot

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#22]
Any iOS real device test fails with appium@1.9.2-beta.2 and XCode10.0 on my iOS real device when taking screenshot..

How to reproduce

```
npm test -- --grep "should work with iOS real device: bundleId=com.apple.camera"
```

Error:

```
   1) Appium
       simpleCheck
         should work with iOS real device: bundleId=com.apple.camera:
     Error: [takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
      at exports.newError (node_modules/wd/lib/utils.js:149:13)
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/callbacks.js:94:19
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

Server log:
https://gist.github.com/NozomiIto/b8fa71b1ce60841e647c89f64eed87b3

result of `npm -g list | grep appium`: https://gist.github.com/NozomiIto/af2966bb9a1b7761e6de9fa838a3cfd3

**Comment by NozomiIto** [comment]
- I've already removed `~/Library/Developer/Xcode/DerivedData/WebDriverAgent-***` and WebDriverAgent app from the device.
- When I use `realDeviceScreenshotter: "idevicescreenshot"` caps, the following error is thrown.

```
  1) Appium
       simpleCheck
         should work with iOS real device: bundleId=com.apple.camera:
     Error: [takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot take a screenshot from the device 'a6b3c05b59692bcbd088d2126a55c860983ae9a3' using idevicescreenshot. Original error: Command 'idevicescreenshot -u a6b3c05b59692bcbd088d2126a55c860983ae9a3 /var/folders/5j/86p6_7p53x92gs6w30cxy3_w0000gn/T/201896-30856-17xjwg8.jr0p/screenshot-a6b3c05b59692bcbd088d2126a55c860983ae9a3.tiff' exited with code 255
      at exports.newError (node_modules/wd/lib/utils.js:149:13)
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/callbacks.js:94:19
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

Appium server log: https://gist.github.com/NozomiIto/88dcacd3531d6a33500dd2e8b163a91d

**Comment by NozomiIto** [comment]
My iPhone is iPhone5 and iOS10.3.3

**Comment by KazuCocoa** [comment]
https://gist.github.com/KazuCocoa/f8a4c28cb88d148e735c9a0dd8330fef
I passed...

```
> appium_regression_check@0.0.1 test /Users/kazuaki/GitHub/AppiumRegressionCheck
> mocha "--grep" "should work with iOS real device: bundleId=com.apple.camera"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
screenshot
page source
find and click
      ✓ should work with iOS real device: bundleId=com.apple.camera (34886ms)
kill Appium server
killed Appium server
kill Appium server
killed Appium server


  1 passing (50s)
```

env

- iPhone SE, iOS 12
- Xcode 10.0

**Comment by KazuCocoa** [comment]
Could your device launch camera, btw?

**Comment by NozomiIto** [comment]
Yes, it can.
Besides, other iOS real device tests also throws the same error.

> iPhone SE, iOS 12
This happens with iOS10 series?

**Comment by KazuCocoa** [comment]
Belows are an error which happened in Xcode 10 build associated with `Error: read ECONNRESET`. 

- https://github.com/appium/appium/issues/11090
- https://github.com/facebook/WebDriverAgent/issues/968

@NozomiIto 
Can you get system log in iPhone during the test running?

**Comment by KazuCocoa** [comment]
in _Session-WebDriverAgentRunner-2018-10-07_101131-06ML1z.log_

```
10:12:00.090 WebDriverAgentRunner-Runner[222:5887] <XCTWaiter: 0x17748f70, state: XCTWaiterStateSucceeded> done waiting
10:12:00.091 WebDriverAgentRunner-Runner[222:5887] Canceling watchdog for <XCTWaiter: 0x17748f70, state: XCTWaiterStateInProgress>.
10:12:00.091 WebDriverAgentRunner-Runner[222:5887] <XCTWaiter: 0x17748f70, state: XCTWaiterStateSucceeded> cleaning up `Request screenshot`
10:12:00.091 WebDriverAgentRunner-Runner[222:5887] Using legacy screenshot path, clipping image to rect {{0.0, 0.0}, {0.0, 320.0}} (scale 2.000000.1, scaled rect {{0.0, 0.0}, {0.0, 640.0}})
2018-10-07 10:12:00.099709+0900 WebDriverAgentRunner-Runner[222:5887] CGImageCreateWithImageProvider: invalid image size: 0 x 0.
Oct  7 10:12:00  WebDriverAgentRunner-Runner[222] <Error>: CGImageCreateWithImageProvider: invalid image size: 0 x 0.
10:12:00.115 xcodebuild[42728:1892799] 📱<DVTiOSDevice (0x7f818eac20b0), NozomiのiPhone, iPhone, 10.3.3 (14G60), a6b3c05b59692bcbd088d2126a55c860983ae9a3> ############## DID EXECUTE #################
10:12:00.122 xcodebuild[42728:1892799] <IDETestOperationCoordinator: 0x7f818eb2ebe0> finished receiving data from testing launch session
10:12:00.122 xcodebuild[42728:1892799] <IDETestOperationCoordinator: 0x7f818eb2ebe0>: _considerFlushingDelegateBlockQueue - nothing to flush
10:12:03.783 xcodebuild[42728:1892799] Handling Crash: WebDriverAgentRunner-Runner (222): <external symbol>
10:12:03.783 xcodebuild[42728:1892799] Test Runner crashed
```

Maybe, WDA failed to capture images...?

**Comment by KazuCocoa** [comment]
@NozomiIto 

- 1.9.1 had no issue for the taking screenshot, right?
- Can you run tests with https://github.com/appium/appium-xcuitest-driver/commit/32fa1471f52bd5011ca464e71fa6b4fe3f4c1379 on your branch?
    - it means please specify `2.95.0` for appium-xcuitest-driver by manual

**Comment by NozomiIto** [comment]
> it means please specify 2.95.0 for appium-xcuitest-driver by manual

It seems that appium-xcui-test-driver@2.95.0 works.

Since the combination of appium-xcui-test-driver@2.95.0 and appium@1.9.2-beta.2 throws babel version mismatch error, I checked out 1.9.2-beta.1 branch and rewritten package.json a little.

- package.json: https://gist.github.com/NozomiIto/6120bb8977707faa020ae3fc1fb3f267
- Appium server log: https://gist.github.com/NozomiIto/e5f4d68ebd1f91d7ef9004f5dc21f311

**Comment by NozomiIto** [comment]
As you can see in https://github.com/Magic-Pod/AppiumRegressionCheck/blob/master/test/testAppium.js , I don't specify mJpegserver port caps.

**Comment by KazuCocoa** [comment]
Thanks.
What about running https://github.com/appium/appium-xcuitest-driver/commit/b1c45de0c23051398fe13614ac505a5cef6a9660 ( _appium-xcui-test-driver@2.96.0 _ )?

---

https://github.com/appium/WebDriverAgent/compare/7fc54afc858c94b061d5983cbef02aca92c0a933...dcd88a12ac6bee6614df7187bf57af485fc66204

**Comment by NozomiIto** [comment]
@KazuCocoa 

Failed with appium-xcuitest-driver@2.96.0

```
  1) Appium
       simpleCheck
         should work with iOS real device: bundleId=com.apple.camera:
     Error: [takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
      at exports.newError (node_modules/wd/lib/utils.js:149:13)
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/callbacks.js:94:19
      at /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

result of `npm list`: https://gist.github.com/NozomiIto/ab3977c2b6485851af0e946ffb6e5764 

server log: https://gist.github.com/NozomiIto/2d4493c896d126fabf16e5b864c21fb4

**Comment by KazuCocoa** [comment]
Thanks. I assume something happened when WDA drop Xcode 8 support.

Will take a look further

**Comment by NozomiIto** [comment]
Thank you 😄

**Comment by KazuCocoa** [comment]
@NozomiIto 
Can you try again with https://github.com/KazuCocoa/appium-xcuitest-driver/tree/km/revert ? The branch is the latest, but I've reverted one commit between 2.96.0 and 2.97.0.

**Comment by NozomiIto** [comment]
@KazuCocoa 

I just checked out [latest master](https://github.com/appium/appium/commit/ef7a1b17124966dbb87442d7356614791fe5e9ce) and overwrote `appium/node_modules/appium-xcuitest-driver/WebDriverAgent` with [your webDriverAgent](https://github.com/KazuCocoa/WebDriverAgent/tree/km/revert-upstream).

Then, the test passed 😄 

Appium log: https://gist.githubusercontent.com/NozomiIto/93f1fd19a11b3547555c689dd0708f97/raw/5e619aa7c42b2b70ab74bc78aea07a433e44656b/Appium%2520log

**Comment by KazuCocoa** [comment]
Thanks! 
Will ask another member or try to fix it by myself.

**Comment by KazuCocoa** [comment]
I ensured.
We'll drop Xcode 8 in the next release. iOS 10.3 has been dropped by Xcode 9. So, we can't guarantee iOS 10. (We 've supported Xcode 8 over a half of year after WDA dropping it...)

If you'd like to support it, I recommend you to use the reverted version in your branch and release it to your env.
@NozomiIto

**Comment by KazuCocoa** [comment]
ah... so, we can see many errors in your log...

**Comment by NozomiIto** [comment]
Thanks!

XCode9 still supports iOS10.3.
And I cannot upgrade OS version of my iPhone since it is iPhone5S.

But if Appium guys won't support iPhone5S anymore, I will use my iPad for my real device test from now on instead. (And Magic Pod will mark iPhone5.* or earlier as deprecated).
iPhone4 and iPhone5 support will be dropped by Apple soon like [iPhone3](https://www.gizmodo.jp/2015/05/iphone_3g3gs.html)?

**Comment by KazuCocoa** [comment]
Did you install Xcode 9 from clean env?
If you've installed Xcode 8 in your machine now/before, lower images are remaining. My machine also can get iOS 8 and 9 images even I uses Xcode 10 since I've installed Xcode 8 and 9.

> But if Appium guys won't support iPhone5S anymore

No. Appium (And WDA) only follows Xcode versions. Apple supports only the latest Xcode versions. Thus, they support only Xcode 10, basically. But we're supporting 2 versions as possible, Xcode 9 and 10 in this case. We don't restrict device names. Supported OS versions follow the limitation.

Apple support iOS 12. They provide the version for iPhone 5s, too. So, in this case, we can sey Apple support iPhone 5s x iOS 12.

> iPhone4 and iPhone5 support will be dropped by Apple soon like iPhone3?

They already dropped to support them since they don't support over iOS 11 to them.
https://9to5mac.com/2018/06/04/ios-12-supported-devices/
http://iossupportmatrix.com

**Comment by KazuCocoa** [comment]
If your "support" means including only security update, then Apple supports iOS 11, perhapse. (not sure cirrent iOS 10 status though)

**Comment by NozomiIto** [comment]
Sorry, my device not iPhone 5S but iPhone5, and iOS12 does not support iPhone5S.

**Comment by NozomiIto** [comment]
> Did you install Xcode 9 from clean env?

Oh, yes.

> If you've installed Xcode 8 in your machine now/before, lower images are remaining. My machine also
> can get iOS 8 and 9 images even I uses Xcode 10 since I've installed Xcode 8 and 9.

Ah, iOS10.3 is not included if I install Xcode10.0 as my first install? I see, thank you.

**Comment by NozomiIto** [comment]
I will try the regression test with latest master and my iPad tomorrow night.
I hope it would work.

**Comment by KazuCocoa** [comment]
Yes, it's Xcode env logic > Ah, iOS10.3 is not...

**Comment by NozomiIto** [comment]
iOS11.3 real iPad passed all test with https://github.com/Magic-Pod/appium/tree/v1.9.2-beta2.16. I will use this version for the next Magic Pod version. Thank you!
