### ISSUE TITLE
Cannot find element and retrieve correct UI tree on some Android real device

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#23]
On some Android real device, a user cannot find the UI element by findElement command and retrieve correct UI tree by source command.

- automationName: uiautomator2
- Java version: 1.8.0_171
- Android SDK installed on PC: 27.0.3
- Android OS version:  5.0.2
- Device API level: 21
- Result of find element: fail to find element despite the element apparently exist
- Source command result is like 

```
<hierarchy rotation="0">
<android.widget.FrameLayout scrollable="false" long-clickable="false" focused="false" clickable="false" password="false" class="android.widget.FrameLayout" checkable="false" index="0" checked="false" package="xxxx" selected="false" enabled="true" bounds="[0,0][1080,1776]" instance="0" focusable="false" />
</hierarchy>
```

- The user tried to retrieve UI tree by uiautomatorviewer. But when clicking the retrieval button on the uiautomatorviewer, the following error is thrown: `Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!`

- But when retrieving UI tree by `~/Library/Android/sdk/platform-tools/adb shell uiautomator dump` and `~/Library/Android/sdk/platform-tools/adb pull /sdcard/window_dump.xml ~/Desktop/ui.uix`, correct UI tree like the following was obtained.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hierarchy rotation="0">
  <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="**.**.**.**" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1776]">
    <node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="**.**.**.**" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1776]">
      <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="**.**.**.**" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1776]">
      
      ...skipped....
      
      </node>
    </node>
  </node>
</hierarchy>
```

**Comment by NozomiIto** [comment]
Thanks! I will try it later

**Comment by KazuCocoa** [comment]
It helps to investigate the cause, in addition, hopefully.

**Comment by KazuCocoa** [comment]
1. uiautomator2 has been improved to get page source. It uses both searching elements and gets source.
2. Espresso driver calls hierarchy implemented in Espresso. The logic is a bit different from uiautomator2's one because of different API in google framework side.

**Comment by NozomiIto** [comment]
Thanks! 
Currently, communication with the user about this trouble is pending several months and I concluded this is not so critical for the user.
So can I just close this? I will ask an user to try the latest Appium if similar problems happen again.

**Comment by KazuCocoa** [comment]
Yes. Thanks
