### ISSUE TITLE
terminateApp command cannot receive timeout option

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#35]
http://appium.io/docs/en/commands/device/app/terminate-app/#terminate-app says terminateApp command supports timeout option. But when I used this option, the following problem happened.

My code:

```
const callbacks = require("wd/lib/callbacks");

driverWd._jsonWireCall({
    method: 'POST',
    relPath: '/appium/device/terminate_app',
    data: {appId: ***', timeout: 10000},
    cb: callbacks.simpleCallback(function(err) {
    if (err) {
        reject(err);
    } else {
        resolve();
    }
    })
});
```

This threw the following error on Android:

`[MJSONWP (2c3f1a19)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you sent ["appId","timeout"] [Thread-1]`

I guess this is due to https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L463.

**Comment by KazuCocoa** [comment]
The parameter should be `options.timeout`
