### ISSUE TITLE
Taking screenshot sometimes fails for iOS system alert

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#5]
Similar to https://github.com/Magic-Pod/AppiumRegressionCheck/issues/3

<img width="339" alt="2018-03-23 11 46 41" src="https://user-images.githubusercontent.com/4276719/37808843-e60482ae-2e8f-11e8-9c4d-710a49086ec8.png">

For some system dialog, which cannot be background, sometimes screenshot command throws the following error on the iOS real device:

client:

`Error: [takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command.`

server:

`To screenshot a frame, it must have non-0 area.`

full log: https://gist.githubusercontent.com/NozomiIto/032e5ff39980a12a5fabb63b17299c3b/raw/cac486a116eb95d21b1089777e4d760c38ad64d0/AppiumServerLog

## Environment

- result of `npm list | grep appium` for Appium server: https://gist.github.com/NozomiIto/8ee14462548860f3e043e5d327bd41d1
- Appium version: [01eae28](https://github.com/appium/appium/commits/master), which is the latest.
- iOS real device iPhone5 x iOS10.3

## How to reproduce

Like https://github.com/Magic-Pod/AppiumRegressionCheck/issues/3, I encounter this problem only just after cleaning WebDriverAgent state.

`APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep "AppiumRegressionTestApp.ipa"` reproduced the problem for me.

**Comment by KazuCocoa** [comment]
Similar to https://github.com/facebook/WebDriverAgent/issues/845 ?
If so, it's kind of timing problem.

The latest Appium have the below command. With Xcode 9, you can check the app's active status via `mobile: queryAppState` and what about take a screenshot after making sure the status is `4`?
https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/#mobile-queryappstate

@NozomiIto

**Comment by NozomiIto** [comment]
@KazuCocoa 
I confirmed this error happens even if app state is 4 and even if retrying taking screenshot manly times..

With the latest test code (which contains app state printing logic and capture retry logic), I still sometimes encounter system pop up error with `APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep "AppiumRegressionTestApp.ipa"`...

client log:

```
(python2) itounozomu-no-MacBook-Pro:AppiumRegressionCheck itonozomi$ APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD=/Users/itonozomi/Documents/GitHub/appium/build/lib/main.js npm test -- --grep "AppiumRegressionTestApp.ipa"

> appium_regression_check@0.0.1 test /Users/itonozomi/Documents/GitHub/AppiumRegressionCheck
> mocha "--grep" "AppiumRegressionTestApp.ipa"



  Appium
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
launch Appium server with JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
    simpleCheck
Current iOS app state is 4
screenshot
{"message":"[takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command.","status":13,"cause":{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while process...
try to take screen shot again
{"message":"[takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command.","status":13,"cause":{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while process...
try to take screen shot again
......
```

server log:
https://gist.githubusercontent.com/NozomiIto/52f3a204d2f6d3aca040099f75d0393a/raw/3cbf0ea6d8e470afbff4c8fceec12a380af71ff9/server%2520log

**Comment by NozomiIto** [comment]
As described in https://github.com/facebook/WebDriverAgent/issues/845#issuecomment-366351623, session less screenshot is also affected by this problem..
Since I use session less source and screenshot for XCUITest, this problem is critical for me..

**Comment by KazuCocoa** [comment]
I tried 5 times, but I wasn't able to reproduce it... Does it work fine with iOS11?
https://github.com/KazuCocoa/AppiumRegressionCheck/tree/investigate-%233

I'll try with iOS 10 simulator.

**Comment by NozomiIto** [comment]
- I have never encountered this trouble on simulator for any iOS version, so maybe this never happens for the simulator of any iOS version.
- I'm not sure if it happens on iOS11 real device. I will try on my iOS11 real device iPad.

**Comment by NozomiIto** [comment]
@KazuCocoa You use iOS11.3, right?

**Comment by KazuCocoa** [comment]
yup

**Comment by KazuCocoa** [comment]
I repeat 100 times: https://github.com/KazuCocoa/AppiumRegressionCheck/commit/7e14ae2ee141b81536ca6563c3b06d359f6db51b , but it works fine.

**Comment by NozomiIto** [comment]
Thanks for your investigation. I will try it on my environment later..

**Comment by NozomiIto** [comment]
It seems Appium1.8.0-beta4 does not cause this problem. (I tried on my iPhone and found it always worked well)
I will close this now, and will reopen if it happens again.
Thank you!!
