### ISSUE TITLE
Apk signing fails with Java9 if Appium server path includes space

### ISSUE THREAD

**Issue by NozomiIto** [Magic-Pod/AppiumRegressionCheck#9]
I found both apksigner and sign.jar call fail with Java9 if Appium server path contains space character. Since `Magic Pod Desktop` contains space character in its path, I'd like to resolve this problem.

### how to reprocude

Rename appium server dir like to `appi um` and run 
```
APPIUM_MAIN_JS_PATH_FOR_MAGIC_POD="/Users/itonozomi/Documents/GitHub/appi um/build/lib/main.js" npm test -- --grep "Java9"
```
with Java9 installed.

### apksigner error

apksigner error is 
```
Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/Users/itonozomi/Library/Android/sdk/build-tools/27.0.2/apksigner sign --key '/Users/itonozomi/Documents/GitHub/appi um/node_modules/appium-adb/keys/testkey.pk8' --cert '/Users/itonozomi/Documents/GitHub/appi um/node_modules/appium-adb/keys/testkey.x509.pem' '/Users/itonozomi/Documents/GitHub/appi um/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.4.0.apk'' exited with code 1; StdErr: Unexpected parameter(s) after input APK (--cert)
```
(I applied https://github.com/appium/appium-adb/pull/314 to my source code to get the StdErr info)

The full server log is https://gist.github.com/NozomiIto/4d28451b33162344718cea0eff91b511

### sign.jar error 

https://github.com/appium/appium-adb/pull/277 says [sign.jar](https://github.com/appium/sign) does not work with Java9 (I found sign.jar uses `sun/misc/BASE64Encoder` which is not included in Java9). So it is expected behavior.

**Comment by KazuCocoa** [comment]
Sorry for my late took a look.
It worked with `appium-adb@6.6.2` which have your change in the adb command.
@NozomiIto

**Comment by KazuCocoa** [comment]
Feel free to re-open this issue.
